pipeline {
  agent {
    docker {
      image 'python:3.11'
      args '-u root:root'  // optional, to run as root
    }
  }

  environment {
    IMAGE_NAME = "nikhil230/ci-cd"
    SONAR_HOST_URL = "http://localhost:9000"
  }

  stages {

    stage('Checkout') {
      steps {
        checkout scm
      }
    }

    stage('Install Dependencies') {
    steps {
        sh '''
        cd project-2/app
        pip install -r requirements.txt

        # Install curl and unzip (if not already present)
        apt-get update && apt-get install -y curl unzip

        # Download and install Sonar Scanner CLI
        cd /tmp
        curl -L -O https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.9.3.731-linux.zip
        unzip sonar-scanner-cli-4.9.3.731-linux.zip -d /opt
        export PATH=$PATH:/opt/sonar-scanner-4.9.3.731-linux/bin
        '''
    }
    }

    stage('Static Code Analysis') {
    steps {
        withCredentials([string(credentialsId: 'sonarqube', variable: 'SONAR_TOKEN')]) {
        sh '''
            cd project-2/app
            # Make sure PATH includes Sonar Scanner
            export PATH=$PATH:/opt/sonar-scanner-4.9.3.731-linux/bin

            # Run analysis
            sonar-scanner \
            -Dsonar.projectKey=flask-app \
            -Dsonar.sources=. \
            -Dsonar.host.url=${SONAR_HOST_URL} \
            -Dsonar.login=${SONAR_TOKEN}
        '''
        }
    }
    }


    stage('Build Docker Image') {
      steps {
        sh '''
          cd project-2/app
          docker build -t ${IMAGE_NAME}:${BUILD_NUMBER} .
        '''
      }
    }

    stage('Push Docker Image') {
      steps {
        withCredentials([usernamePassword(
          credentialsId: 'docker-cred',
          usernameVariable: 'DOCKER_USER',
          passwordVariable: 'DOCKER_PASS'
        )]) {
          sh '''
            echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
            docker push ${IMAGE_NAME}:${BUILD_NUMBER}
          '''
        }
      }
    }

    stage('Update Deployment Manifest') {
      steps {
        withCredentials([string(credentialsId: 'github-token', variable: 'GITHUB_TOKEN')]) {
          sh '''
            sed -i "s/replaceImageTag/${BUILD_NUMBER}/g" project-2/manifest/deployment.yaml

            git config user.email "jenkins@ci.com"
            git config user.name "Jenkins CI"

            git add project-2/manifest/deployment.yaml
            git commit -m "Update image to ${BUILD_NUMBER}"
            git push https://${GITHUB_TOKEN}@github.com/nkhl99/cloud-and-devops-projects.git main
          '''
        }
      }
    }
  }
}
