pipeline {
  agent {
    docker {
      image 'python:3.11'
      args '--user root -v /var/run/docker.sock:/var/run/docker.sock'
    }
  }

  environment {
    IMAGE_NAME = "nikhil230/ci-cd"
    SONAR_HOST_URL = "http://localhost:9000"
  }

  stages {

    stage('Checkout') {
      steps {
        checkout scm
      }
    }

    stage('Install Dependencies') {
      steps {
        sh '''
          cd cloud-and-devops-projects/project-2/app
          pip install -r requirements.txt
          pip install sonar-scanner-cli
        '''
      }
    }

    stage('Static Code Analysis') {
      steps {
        withCredentials([string(credentialsId: 'sonarqube', variable: 'SONAR_TOKEN')]) {
          sh '''
            cd cloud-and-devops-projects/project-2/app
            sonar-scanner \
              -Dsonar.projectKey=flask-app \
              -Dsonar.sources=. \
              -Dsonar.host.url=${SONAR_HOST_URL} \
              -Dsonar.login=${SONAR_TOKEN}
          '''
        }
      }
    }

    stage('Build Docker Image') {
      steps {
        sh '''
          cd cloud-and-devops-projects/project-2/app
          docker build -t ${IMAGE_NAME}:${BUILD_NUMBER} .
        '''
      }
    }

    stage('Push Docker Image') {
      steps {
        withCredentials([usernamePassword(
          credentialsId: 'docker-cred',
          usernameVariable: 'DOCKER_USER',
          passwordVariable: 'DOCKER_PASS'
        )]) {
          sh '''
            echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
            docker push ${IMAGE_NAME}:${BUILD_NUMBER}
          '''
        }
      }
    }

    stage('Update Deployment Manifest') {
      steps {
        withCredentials([string(credentialsId: 'github-token', variable: 'GITHUB_TOKEN')]) {
          sh '''
            sed -i "s/replaceImageTag/${BUILD_NUMBER}/g" cloud-and-devops-projects/project-2/manifest/deployment.yaml

            git config user.email "jenkins@ci.com"
            git config user.name "Jenkins CI"

            git add cloud-and-devops-projects/project-2/manifest/deployment.yaml
            git commit -m "Update image to ${BUILD_NUMBER}"
            git push https://${GITHUB_TOKEN}@github.com/<YOUR_GITHUB_USERNAME>/<REPO_NAME>.git main
          '''
        }
      }
    }
  }
}
