sonar.projectKey=flask-cicd
sonar.projectName=flask-cicd
sonar.projectVersion=1.0

# Source code location
sonar.sources=app

# Python specifics
sonar.language=py
sonar.python.version=3
sonar.sourceEncoding=UTF-8
